version: '3'
services:
  ansible:
    image: aymen-g/ansible
    container_name: ansible
    volumes:
      - .ssh/id_rsa:/id_rsa
      - ../ansible-780t/:/home/root/ansible/
    environment:
      - ANSIBLE_VAULT_PASSWORD=supersupersecret
      - ANSIBLE_USERNAME=ansible-ag

