version: '3'
services:
  ansible-container:
    image: aymen-g/ansible
    container_name: ansible-container
    volumes:
      - /chemin/vers/le/repertoire/du/projet:/chemin/vers/le/repertoire/du/projet
      - ~/.ssh/srvIDA:/home/ansible-ag/id_rsa
    environment:
      - ANSIBLE_VAULT_PASSWORD=Melanie2!
      - ANSIBLE_GID=25055  # GID de votre groupe ansible
      - ANSIBLE_UID=25055  # UID de votre utilisateur ansible
      - ANSIBLE_USERNAME=ansible-ag
      - ANSIBLE_HOMEDIR=/home/ansible-ag
      - REPO_URL=https://gitlab-forge.din.developpement-durable.gouv.fr/snum/detn/gmcd/ansible-ida
      - GIT_CLONE_DELAY=2  # Intervalle en minutes pour le git pull
      # Vous pouvez ajouter d'autres variables d'environnement ici